version: '3.6'


volumes:
  test_amis_db_data: # ai_teacher_local_redis_data:


services:
  db:
    platform: linux/amd64
    image: postgres
    volumes:
      - test_amis_db_data:/var/lib/postgresql/data
    env_file:
      - .envs/.db
    ports:
      - "5432:5432"

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    entrypoint: /entrypoint
    volumes:
      - ./src:/test_admin
    ports:
      - "8086:8086"
    depends_on:
      - db
    env_file:
      - .envs/.db
      - .envs/.app
    command: /start
