#!/bin/bash

if [ "$DATABASE" = "postgres" ]
then
    echo "Waiting for postgres $POSTGRES_HOST $POSTGRES_PORT ..."

    while ! nc -z $POSTGRES_HOST $POSTGRES_PORT; do
      sleep 0.1
    done

    echo "PostgreSQL started for ai_service!"
fi

exec "$@"
